DROP DATABASE IF EXISTS pos_web;
CREATE DATABASE IF NOT EXISTS pos_web;
SHOW DATABASES;
USE pos_web;

DROP TABLE IF EXISTS Customer;
CREATE TABLE IF NOT EXISTS Customer
(
    id      VARCHAR(8),
    name    VARCHAR(30),
    address VARCHAR(30),
    salary  double,
    CONSTRAINT PRIMARY KEY (id)
);
SHOW TABLES;
DESCRIBE Customer;
